### ISSUE TITLE
There is no select all operation

### ISSUE THREAD

**Issue by ryanartisan** [hexters/hexa-docs#1]
I may have too many resources. You need to select multiple permissions at one time, this is very important!

![WX20240705-214004@2x](https://github.com/hexters/hexa-docs/assets/100556331/b69dab68-6df5-4ce9-8ef1-b9b9e594b1cc)

**Comment by hexters** [comment]
Hi,

Thank you for using this plugin, and thank you for providing feedback.

Indeed I had planned that, I have updated it in version V1.3.2

If there are problems in the installation process due to ppmarket.org, please contact me again.

**Comment by ryanartisan** [comment]
HI, It cannot be installed normally, what is the problem?

**Comment by hexters** [comment]
> HI, It cannot be installed normally, what is the problem?

Please try to reinstall package.

Comment the plugin in your Admin provider

```php
// ->plugin(Hexa::make())
```

And reinstall package

```bash
composer remove hexters/hexa
```

```bash
composer require hexters/hexa
```
