### ISSUE TITLE
Gate problem

### ISSUE THREAD

**Issue by ankorinek** [hexters/hexa-docs#2]
I installed the package and added the code to the panel and resource as shown in the help. I can login with the hexa admin user account, but then get the following problem:

`App\Policies\BranchSectionPolicy::viewAny(): Argument #1 ($user) must be of type App\Models\User, App\Models\Admin given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 811`

**Comment by hexters** [comment]
Maybe because Hexa is using `guard auth:admin`, you can write the `viewAny` function like this:

```php
public function viewAny(User|Admin $user)
```
